# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f086b5d6df5fb4ee99b93e926a995c16e679782afd56c079dcf6a62f7488b63782676118a281c19a15c93d7e3a5d3f1919e1dbc2635d83eb4b3d9c7678d5e8

test:
  secret_key_base: 4103ba05f468fec065747932e62db1aba79eeed1de25c90dffd87ba15d8e1ff69621d6d514f4838918bde1ca9ed00820f016067fc0bd5b29e1cd3fbd47506a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
